export default Routes = {
    PHONE_NUMBER: 'PHONE_NUMBER',
    VERIFICATION: 'VERIFICATION',
    CHAT: 'CHAT_DASHBOARD',
    CHAT_DETAIL: 'CHAT_DETAIL',
    DISCOVER: 'DISCOVER_DASHBOARD',
    SETTINGS: 'SETTIGNS_DASHBOARD',
    DASHBOARD: 'DASHBOARD',
    SETTING_DETAIL: 'SETTING_DETAIL'
}
